global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # API Backend
  - job_name: 'aluvi-backend'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  # PostgreSQL Database
  - job_name: 'aluvi-postgres'
    static_configs:
      - targets: ['db:5432']
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'aluvi-redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Nginx Web Server
  - job_name: 'aluvi-nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s

  # Node Exporter (sistema)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s

# Alerting
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Remote write (opcional)
# remote_write:
#   - url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"